### ISSUE TITLE
Multiple DLP calls on Google Docs

### ISSUE THREAD

**Issue by gregstoll** [chromium/content_analysis_sdk#106]
Hi! I'm a software engineer working on Firefox to integrate this SDK so DLP agents can support Firefox as well as Chromium.

One thing I've noticed is that when copying text from a Google Doc and pasting into another Google Doc, there are multiple calls to get the clipboard contents with different formats, and each one triggers a request to be sent to the DLP agent. Since many of these calls are from Javascript, Firefox shows a busy dialog each time a request is sent, which can make for a jarring experience.

A way of working around this would be to send one DLP request with the whole contents of the clipboard, but the protocol only seems to support a single string being sent at a time.

Is there a recommended way of dealing with this?

For reference, when I copy text from a Google Doc and paste into a different Google Doc, here are the calls I'm seeing that trigger DLP requests:

- Javascript call to DataTransfer.getData("application/x-vnd.google-docs-document-slice-clip+wrapped")
- Javascript call to DataTransfer.getData("text/plain")
- Javascript call to TextEvent.getData()
- a "regular" paste being done on an HTMLEditor

**Comment by nancy-lan-xiao** [comment]
Hi Greg,

The current design of the sdk is that one user action may trigger multiple DLP requests and we use `user_action_id` and `user_action_requests_count` in [analysis.proto](https://github.com/chromium/content_analysis_sdk/blob/main/proto/content_analysis/sdk/analysis.proto) to keep track of those requests.

In Chrome, we don't show dialog whenever a request is sent, instead the dialog is shown ([code location](https://crsrc.org/c/chrome/browser/enterprise/connectors/analysis/content_analysis_dialog.cc)):
1. when the analysis duration is longer than 1 second.
2. when the blocking mode is turned on
3. when the analysis result is not success.

If it is possible, updating the browser dialog logic is the most straightforward solution, otherwise, you might have to branch off from the SDK with updated proto on both client and browser side.

Hope it helps,
Nancy

**Comment by gregstoll** [comment]
Thanks for the info!
